-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go fmt`, requires golang"
-   id: go-vet
    name: 'go vet'
    entry: run-go-vet.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go vet`, requires golang"
-   id: go-imports
    name: 'go imports'
    entry: run-go-imports.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `goimports`, requires golang"
-   id: go-lint
    name: 'go lint'
    entry: run-go-lint.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `golint`, requires https://github.com/golang/lint"
-   id: golangci-lint
    name: 'golangci-lint'
    entry: run-golangci-lint.sh
    types: [go]
    language: 'script'
    pass_filenames: false
    description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"
-   id: go-unit-tests
    name: 'go-unit-tests'
    entry: run-go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"
-   id: go-generate
    name: 'go-generate'
    entry: run-go-generate.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go generate`, requires golang"
-   id: go-mod-tidy
    name: 'go-mod-tidy'
    entry: run-go-mod-tidy.sh
    pass_filenames: false
    language: 'script'
    description: "Runs `go mod tidy -v`, requires golang"
-   id: go-get-update
    name: 'go-get-update'
    entry: run-go-get-update.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go get -u -v ./...` to update all dependencies, requires golang"
-   id: goimports-reviser
    name: 'goimports-reviser'
    entry: run-goimports-reviser.sh
    files: '\.go$'
    pass_filenames: false
    language: 'script'
    description: "Runs `goimports-reviser -format [args] ./...` to format all go files"
-   id: revive
    name: 'revive'
    entry: run-revive.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `revive [args] ./...` to lint all go files"
-   id: force-mod-version
    name: 'force-mod-version'
    entry: run-force-mod-version.sh
    pass_filenames: false
    language: 'script'
    description: "Force go version in go.mod and go.work files"
