repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
